apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bookstack-mariadb
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    mariadb-password: AgBVL45hvMajwXqdSiwsaC7fV2GiO3on5asdrZswXKFwZArrQSHocs30gIVdwdXE7aRMChF4PqIeSSxQsABRfIA95ePF/gcIoe16Ts4eL2AMMB7G4I2OeR104IKfOMld9uFA7s1r1y5NUhvzliYHmNhrL34ppuuQ1Xlowls6uIPhbewKa9khcaBkWll5T+kFwLm5BKTD3oVgViPiP9ikcu0p04ZPe4KAdNB6117Sr9f/zsV9mGrjo2BUT9UyfUkUO2SS9pXzB7QI2Qic9VA6w9sUo6/jsLuL7XAaCOyIElOU78iIW7D9c0ddZZyHsLHaIIRtSQ/k/P8FQdH/blt1hMG7NidC6a2f5HCW2OGxdB0KhKg8D53GajeUBXD/by3tKTYxZC34s98im7xz8ROgF/hD2/xnz10ytpZFlWTx0yS7LX30DjH1atET83bV/Ei46oTGoIbFKMoFwyXTYB8OBtYVPCs8KE8QIAuAStkhRVvtSnF2SC5WrExOFX0bo8iORHYUpWbdLY9RiVODXVerTt00hFBYN9bp+qG/BzHJa/WYETukRuYcfyeVesr39otQ9IAxhBWvHObIgsWTmKkpWg0Eio8cjB5r4/fX+Harln/Rf2pT23B9TEPJ5d6EtrEfs6Pj8/9N0l//tix5TPTVydN95xsMlZkpnhjfiumR2v1Rp2McnwbpnE+EFMfa9GZ+k2HR8Qw6g+uixNjWdclK5Br+rxI5DXXQ1GIh32FFbXl/iA==
    mariadb-root-password: AgBkx//89BsZvkQMeMt7H9XUIX1JoNvc5/8m2U7og/VXJc6SLo0y7rx9S8Hc5rymrXCCKVMaWqWi0kBNsS+m+3PUyE6s1sND/659P6pORpd/l/CpHDp3eAcM3Rt+47P7q7nqDbC4H8j6T2gJg2qMcgs4T1+jCbPaxcBWs8oyTR5rrJJ5M/ok9vx8MysdBYVeKNjKDyA/4GnibxBVYAsukE8a67/T60sQ67G5TPkGdN7m/FAOYuhYgc7ocMSIiqDyIcT/JvMu/HUcGat9N0nJ99XlIKGWJPcURK1LPk3ZVxawVr4DVT8jVimHEyxptuXk7QDCh/2AZp2G+54LqJiX6lE02hwcbNXtcKRis7TlCHhgrhY+v76r95zt09ofZ6DTtggB0wo4KHhDX7AmMVs9eTVXeT7g2Nne1Q8Vn8jNKcGJTeptGciA6Q719T2l6/rFYiQxQ59Q0XOWomdcg54AhBLQm/y6cjIx4Y7UPugo4L6TlZWj99tR55DXmSeCeH7VnVxcBAaS3RW/obtmaw9+j3zJpX0skN2zjWgUMSnz1MJelbjp/6Mgf0xitllkKgiVNkPHgWHUo0qR/aRK4cOEMzRzG3OuNCoJq0sEKKgv7yEkSvh2rn63gmVfIcX+m0WVItg0bBMDZkKaoq4LYzidCKxq7pT4/r1i2tT3ppk5fKr8mTA0/V6ZAoIy7AeLlSS2iCskPe7EnPo9BcpkdIuRJY1+uDDcUvb6ugGVGXeVWnoyWg==
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bookstack-env
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    APP_KEY: AgABgqyV+tLxUUindhDW7QWS/yu/3wmm1r/f/gTBxPar0yJLHmIOObTaycldyyzYUGIoXysaJmYuTO5bczvm1MvFD3jIAQRuQPFBkVvBUkZt3AU+uKdWzFg80yngUmaiIe2wJ6l/j/lyOsl48dEyuI3da9MSYK7g27zuZMcdNmS2tCPnwS4juu2F5W9vslnmEAFCZH0l2+nTFwawT51YszmHYl1vKj8HEH4HNM+ANbHfBjupHMaTrn1ML3jtU/SCM8ZVFk5uu6XeN0eYdQtEeCiGLRAXMbJOnaMJS7ApKVDHTMSEu1b3Vz6McgNwEc2Cnq/PU2Gcr7LXG5L+hJyoWeVKpL1m7TRQq5vPkryTfGcyLzRII6FcDdusiQ0xiEzJsf6aErZpYtjsL2JFInn9Y7I+vRD/vr2UQX9jxOBQzw4xzcMEQhne/gUVhXpOo9BwHg9CokWNRMjWg+7AMW61KcF5cXE3hfVGut5VjaWM2LnwB5VQUscWDd7qTBkSc1+ZJs4L0NIpGnrUB8IOLm98DbC/kMIiC2/e3fet8MJhyEPF+3wdgT6FzRPr6iIJKepmHZm3R6Rc/aEgolvxL7/cHxdzYGTdv91hZYgjpRN7ZGWFn2RLfeFC3yRDlvOMGcBf9C5DH4lFu0wh43+Xawf5Ms7F9NZ3RLky//qbL+o7FSP2SJQNBJe6kYFkmgJZ2XuTlQiN993vLWmjHh8rZHJbe8TiKYeOvVPAnfgqOabYj4+KnWQiPYy6qIN0DZNRse9b84PeREs=

