apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-database
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    password: AgBnqooFmRpBlsWV9m3NrWx1OQo29GxbAO+8OkjL3EQ0kJ+tDoS3m2fzbApqn2ocSHZTzswMQwBmwt0Ij7bvUyT7t1CYfp/DZxGbYrayixrmi/1cCzQIdGzln1FHE1tqtYHeDksX/jmMNMo8HC6Nwz6t83bjMRkvZGEf0ET+Vp2Pln4juQH0+Oc8upNgYoGrqnovxp1D1vq9eP2RzrYBKSo/bcy+XyHcc2v2RlGkFMV+Et/+WsQlEfmgUDQMj3aRUPUiURF7kY4O3QCvzatr67GDr4FxBrc3IVEDLKbs2rvuTTWyIbf8xpChSuzN4sP9EBdZUCJvp0yVRfo/B3HY+86lnc78hFsoLoRCA9n1F5nw4LIU83gTIHwbr7bBAgaWV/DCSynAzKeNnCZglV6kQ9PXc255TlDSqmEYGS3P0RP4axnJ55WcWdIoCNLWEqUcBxN1GKRZia6VVjpSeYjrgUtcludkvrq7Se9zCXd9kg09cLVuipcTarbEVeMqwWJ6o0p7iw+tTlfoAU6cIIIG35AwFYJ9PkLO7A7URQeVmc8BsNxQSShgTb27dGbVty3EWDrBaoV4QIcR3ttrIECmQxH0KA6/PcbpVJxd07BRHYTTBIkc72mtyP02IS2D88NCldidOcM0hPEfskgC66BWvs6mEigcA0Pzr7LdUFZgHlxT3ecElRj0/YoAF1XQO/iT+h/PYmRWEBO9sDuOsQ8ywVytx24knrawzPGgYRjEUwZj0w==
