apiVersion: v2
name: kube-system
description: Deployment chart for kube-system
type: application
version: "0.0.0"

dependencies:
  - name: sealed-secrets
    version: "2.19.0"
    repository: https://bitnami.github.io/sealed-secrets
