ingress-nginx:
  controller:
    config:
      use-proxy-protocol: true
      proxy-buffers-number: 4
      proxy-buffer-size: 512k # default: 4k
      proxy-busy-buffers-size: 1024k # default: 8k
    kind: DaemonSet
    service:
      type: NodePort
      nodePorts:
        http: 32080
        https: 32443
      externalTrafficPolicy: Local
