gitea:
  image:
    tag: "1.27.1" # renovate: image=gitea/gitea

  replicaCount: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  podDisruptionBudget:
    minAvailable: 1

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: gitea
                app.kubernetes.io/instance: gitea
            topologyKey: kubernetes.io/hostname

  valkey-cluster:
    enabled: false
  valkey:
    enabled: false
  postgresql:
    enabled: false
  postgresql-ha:
    enabled: false

  persistence:
    enabled: true
    claimName: gitea-shared-storage-rwx
    size: 10Gi
    storageClass: longhorn
    accessModes:
      - ReadWriteMany

  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      cache:
        ADAPTER: redis
        HOST: redis://gitea-redis-headless.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
      session:
        PROVIDER: redis
        PROVIDER_CONFIG: redis://gitea-redis-headless.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
      queue:
        TYPE: redis
        CONN_STR: redis://gitea-redis-headless.gitea.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&
      database:
        DB_TYPE: postgres
        HOST: postgres-rw.databases.svc.cluster.local
        NAME: gitea
        USER: gitea
      indexer:
        ISSUE_INDEXER_TYPE: db
        REPO_INDEXER_ENABLED: false
      server:
        OFFLINE_MODE: false
    additionalConfigSources:
    - secret:
        secretName: gitea-app-ini-secrets

  ingress:
    enabled: true
    className: nginx # Required, as otherwise rendered as "".
    pathType: Prefix
    hosts:
      - host: git.home.klaus-meyer.net
        paths:
          - path: /
    tls:
      - hosts:
          - git.home.klaus-meyer.net

redis:
  haMode:
    enabled: false
  storage:
    requestedSize: 8Gi
    keepPvc: true
