apiVersion: v2
name: mailcatcher
description: Deployment chart for mailcatcher
type: application
version: "0.0.0"

dependencies:
  - name: common
    version: 4.1.1
    repository: https://bjw-s-labs.github.io/helm-charts/
