apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-ngx
  annotations:
    tailscale.com/proxy-group: tailscale-proxies
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: paperless-ngx
      port:
        name: http
  tls:
    - hosts: ["paperless"]
