apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-postgresql
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    password: AgAZbSNJHxI/eCfM3ppfj2z2ryxjMPlN2UGNK9+dKE0iritQaG1SleRG5XKV1EVDTDzWFylOkE/vqhuZCHQ858lY/hQmbWlm9BqoV2KFX48b8qrZrMpNiaeKj5vg6YYNPZj2g8fmcaNZNniP2q89bT2FS5KlDZCJN4WOVqQA3O8YMK5RFDCLiGN3eRLsVWj9NWiyL3Pd4OOh/GYpOcJEDxHBX6+tkTB9JQQNBWcE1uHKlaamPf5w6XROxEFl1EbvxsxxHq3QIKDUz5sCtGWooFOtfUhA8nChdm/wWRM9xg31cvDJanI5bQ3TfHJGEclRqYkv0H1/2UBnF2CK7xRwsX9M39/PNMzhTgXfihJghTi4dOGZgXXdFabUUxTCPBlH7Pz/GSg/aCR/8aYSWGk7w84ZQzPvYjTwztzvFtD5G4Q1IDWbhHxESynr4lqMDdVp3idcC/G2JsV7fyviyJkRiLTaEdqfYvMIefpk7nkxSkEogsY0o89mCTc91tMvOmKal8FFqnFmzz5afC6xVFYkE5GfmO4qah5bN9BX3FBO2GyNw+JPvyzA7OL8XDESEwDRkx7UTCCRpiwpQP7FMxrETNE7jBvIfloo2lio+4uVn6cAB6s/eJqdsZdLvi2tvQB8EW6x757rTP42op7MoabLgHK1TaR6XQKIpJzmp3Y6UMvZf6VEUNRzPVRoEfnldpsnWyb5EbbsXKDz8VS+q/hnFcSY2OKqJW2Nd0Dyzh39yQQ6mA==
