apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-postgresql
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    password: AgACDost8Rvc13KGuA2ibDuEUuNYYu5BG3Tbi+CiSWHXRlminfto8szf4geEChG4FqxXC8PQHtnvgC1l3KrBOs1fQA5mVLRhh99fzddDz4c45bqBUXCcTLwvfL2PJra0vabH1HbA0fxUDwN8gCPO5pSPGTVkSWBQarG4PUOZJbcvFk6WVmlAfjMFp65PxEwKBRUwlaR1N/sWMsMc4kLCGzCttDHVE11SI8lJ4nXoWO/y3QlJ755E4fgj7A6WWWWk4wv7Jm9E2Turwo6atYMTVOXQqjcYVM5W6Wn9+kCrVv94NFp1d9dhhk/4+QigFEhJipZzGe+mn8SUFPRU52YZRNt3uOSN8x8jtejwTyPhx2vmrjWBp7flfPSqjk4y02xlXqeyiHKqSsXRyhY0tLz+N7YmZOg0oj3avaDbj4ToV9/uIC86JqmK5xtJ5ByQAdso6yEghLUsYmy2HHDC4ZUDbv7Q9x2X6HL5kmoEv9S6aTTc0vyMJbZ9CniahDzHs3vaQhi+E/Ct4/aazVDW0ofrTWa10I3kWdpJ0HbHd3dRpD6Ry70dCdANFQkaxk0bmq7OMeJhi2Fjcv5FBWaBRvgrhe2sW1t0bLkQqpOB68CQbKF5KliYJ7m28ZN4S5ctZo2D2SDqcPm39jKAObdPiXI3d21nJvQvuEFaFDCMXaRAisPE+IIn4tn+miO6VDlLk8yd4ZUf/Fg/D2hStLxK1xp4atlwq8xeFHJUWuHbvzdl4ftnUA==
