apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-postgresql
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    password: AgCok8gqjhP6DuhRBmdcEcQ9JOhjxfCutXBQSaNsvj1TRGBz7GoBWDvVJWgdUfh1+dTW0vaUgIfSBgUI8AD8O1Yic/imoZclDgTcg0GdzBD2G5nUQU8JqrC6/176mEXGNQ8LLVB7TLAvCjNc6KTQkPaQKaGA4O+Main/XT0yxWsqqVZonLkUI5QyyJWo2Y77YnGPiUN6ZJK71BDmUZivsRli77O6fBFbaNOcJnjP43D1XbOw2bmU3PRM7qmieCDMJ+YrzgMKQzhTHJFkdpYoalovo3HW2uB+KsGrnosxdlfzwQ5EWyiFvQR8Q1Xr7nABXZz7ZqucQKDswPAILBFc1GK6Qg92z/nfFrMn35hn5VlHbx4yzfvkwimGVrP3Kvo9Qu2I4OM/+81GjMQ14LqiuiZRqEVhZuxr4SuLQ6AXebUXbd63MCVG85fP4WM3623BsGUfrL+mTNS6dmYGMFqIqHaY/lFDBy3lhhK+q/fKzAJ+pdRbhV91azpm8z+ot/6/ig4YtzY3K4HNMzqsivnzfvbRTAt3MP+KN9oXRhCrllRgI5uKOYxpcBIUcXgDj/Z7i9PwpbXvacTbDCpevYfyXVuUpgcOeqcnk9CxXq8sECqU3Itxp479aBNDW3GaY7zJNx+TNFtzaDAq6jWhRw1psePIp38JUX3pWEjXqhXF9OMT6zlQVKG/YIp6MxPBdvZNdt6S8d83RxyEeZaq13LUv/t6OJ+Ttg8Q1PJsPj6RdfexSgOsX1k9iSSnvfekDPCUnNG+LRY3zGOZMB27iM5gFbi3E6Pxgb7sCuAE5PP+JWxDLD95C+PcD9njz5q9ksMTWELtZJFFHhMHUz0=
