apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    secret_key: AgAoFHuQoRiVrvLll682HHg8uSH9E/wyE0xLWSudlxR70VkziwgIxW63SO8rH19I0N/pZbG0TGgdbHtXzc1b5oLzuv2+LqgP24tWlhM0Q5agWYW7GU7NqV1gpiY8EBNclLSwCgW3EvXEtugkTe9yGOcqONiCp61Nj6PY4fPyV6XhDzsNl+t0/lHP0zUwd2HbTb8JwJAEuVd5NSHpSB1Z+rRNts+1EZsQtcSPfKi0lPqKdcYaSRtF+TIDeb2EdureAN+g/ZqC2TjeeHOWJX0KWWGMVG+y8zKbv+RytXkJtD4FoopiMjyZldpO6DAO/n+X1p/pypxZmtFzv4nj6cI0Z7mgs39faE0mQeLU4q+qeM755Y8HMUUcKXkxzazC09SG+u6s28AZtAMgmt+di+Q1RCy3hz61zih7GQyjjz/2ivsUJHKUTa4vz99N9447hkt4+rlKIIA8njvSMTfUPEtlxV4scr/JxsCxeZ95O7LG5xifenm6s+5f3u1pWFA5YU8ibNhtfqJzdSRxcIUNgaZAbxK9ITSVB2xyf2//MvENpPMCoDpcuDv3Y9x8cbSwQ788xN7UyxbdPFj+83PA3JWlZvjDL0KPrkcsatpGpc5EyOXP/wBzSsj27ZQ6YqH3Oz+eadSt7jYfKiEQh81QOCB+NoUuRk9/f4oULE9VXYvSoqZ+pCS3EfAJv4qWSwp1LtiT2hsnXDgfDtXSfGkujyy0sHCQsyQfJUoZChO3NyAh+z+gBwEfOtxmEWjTSgp0KSOxjYajmO3yzG5BBdOLqynyt+JdHlf+2wZw8qbqqKmmHcodTbFQQ7h5Xw==
