apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: planka-secretkey
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    key: AgCgTu1780cankKQA4nscNxqn2BeKhhpqRwHUkOZqS4CoxKUhkMNpgFv+kDiuyB28NqRq/yk6xjv5yNA5OmGbcgxOrKm2DwB50bWOOHQ3fQW0OQLXylOGPUupnIzpS/W98RA0HlbkPdk/jTXtu3iaaKhK2+9dPjG7EFPszfo2b72RDD8zS05cIXl9PwutZz0EuHNdMG7LdZ5BYE6TwqIXV6RkItJ3d4THrIp1/Ll2QhRnO5iY/ceWv5JatOd6q7OEL76JgDARHP83lwPUw6eUc4KEFw8nbTVqPfAEe/+5cNJtgE3gLIVdd2jOlXa8rdHn2xeAX79Jn5se7+1LFuHciUaSoqzaUKM2aHyjr6rQ6wHXJ5vxRiXkPpuVqu8xX80h/fTRL39DWqsbY3hGWGvvFLugmlFJNnm5T7AZkH5cjuqTIBX3QxZKoypAAYC4TEr+7THW3QUUFa5EX0T7MBij3cHzhafxAMi1/uKL8avr0K5q6nHHqAG6szpK6j6zFgiIDLnzseNVthwqjgq7bCK4Dr9MUMbbTpIJ97/yY6FQbQfnYYA/omLYk8GYO8v3ElInYtugz0PionfCearfZL4UFX8xFTJ7aiAsGSsCEuIZxYSXivpSIJZjomDQ6ZQkhX/9JAe9eDywB7HgS/ovuZflS/0y2Eg40l4/kn0tQk0P+VeeqzEcmmwca5qSuiXssJ5qJ7qE5+vtITrbCidH0ZvidzYZdTnHWFKeTbDUB3fO0dN+wvU1kZuTUU4C2iIiUPP8DIQwLDhWvVOZuEwrfPvEfEG/ywFxMYR10EJ17Szle5RAozsw0wzS6/GD7A68N6nQFMuSCZD8fZvcGcvegC7eNVVHDufNf6ECVcSn3wiQbSy+A==
