apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: planka-dburl
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    uri: AgBJH34D3RTkIyC3HkVPD/4uouaZdOI+21PWwfACHJlsWN2kSkSqKeemW2aL0ocWSQ5ASCTcBRAw/ZikmR4YBcD08BTQdf84rYR5jpxKmz8IUeIzaDmOkW5xVdMuYu2lOrArs5NrRPZIMNzanjsAgOaG/ANrK2FybdbSBk4UZDHWYRWQozmYA0RprIsKj7WXSB4O2iyvTrqhRz1PUBB1ModFkKYLcQ1Ih5zxYCpqIxrqgZfQFY5VxFOM+8hWpXS8SBzQQaW/4RZcDpU2u5vc3zoQ2waGiyLVWWQL8KBX1PFbsJU3yX+OqpiE//plnp2/d1CJH5dWL/4Bwj1dTT1GGzD0qZzo5KT1tDyCZONzUzvLj5VnxXsGlfpNWdU/aWeYRN0srzzbWZQ+Xn6Dhgd8qhG2MBvWCHzB4rZvMozGRGv4PZ1vOo975aFadxZ1LUZzGR4lp+kAm3pxKZS12/B/+D5+LUWje/uhYNM2WmZYKl12MniIolPLksgHTPmux3fbxLZx8N49evZlZpaPTzFcaaURvEBrR+fZUDkUQeZ6qCdGepCdylxzVWWp8/75AkDFULbwU4NcvLfK9RAXQHXOmLvPV3c/TJ7aRQZ2ND05eHcrDEqKnbZvu58IA2zgf+gxb/xc0BU2K9P+rqyOxaJyYD3McoYCOp3hx/rNalMeXioC3023ijmSGwvD8VEeU+CuEr/29e+PQxWaxwEFlckACSoA+b4+TcW2sW4Z6TcDtI6XsIhfh/9+q3zymSLUHV9sFu0AtVWHGiFYWlhrx11sYWOpWFMZG/4Y3UaM7xU6DvHxapje5Y2Ea4RhIv543dUozeINaG9U25M=
