apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: planka-secretkey
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    key: AgCew9YAnKFxg885DA991VfNni/uaIKsVyAVqHgwy+l6d9H90M7N1+IEzAiTtDg7f/5jRYCIcmbDKYVLsTmdriQQSMLbMsurwAOZ531rAelQ4TVTQeR2dwsGPAO/4nz9gMgMwhnOv5Zb8v+PWpkYkcT+9ubDTebKr59sSWJl+N3NojQqXwYDzpJ2fRrbuwLXtxhHNHFoZ6RXZgoDsMxXi4wgVXYJy/bITZ2NwH9XsPgwqwXMutzU5+oPnyMHR3Yar6OvnG/mlDDWuVeqpoZG2e7H9edNZFX0Uy7izKrugfaaeq2UayvoctWrlLITZP9gXxAKVBUvyzSjEHLQxzYcA4i9aPE1XQeXod+l9ybUzOr8vabHqCe2kQJt+P+eHaHH2DeY2fGxQvbahC4s7NqNawJqYIJA3MI5BaizFV2xbcsdp4OmKcaj7wBVGMaEmKJk4h6+ajvIRa+GeFDdB5RRJCn3KVyIArF5R7VwdJM0WtWWqrI2QpVbGnt35SPXOpYiSyuGFQWDy+dJGefHHOM84FBBJBkLDzSV/Lr9htn8/ilw1P1fkUchrxjfQSpGAM05RSYTNhqDvUz+OCwUFlnrOr9n0rCVz4ah0m7UWbI59PZckSfCILS+GomFjmbr4nLOI3Au3UQNDmx7sBvP2CMUmpRqJQSUl7UskAB1TocLyDINGEAjC5BZkXSDI9xLGoih8wTvbPrI35ZDrNPs0dlGVoBoZIp34e0oimoQu+5tRDbd/oN3MwcBLaY7+tJy9jj9DZGlXlHi2g6Klac93QdYSVny
