apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: planka-dburl
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    uri: AgCKBBJi6w1GOZedeursZn/NCEe094WCmkAEsO6gjRogXnsdM36xT6f1Y89h5irNYZg1ZSVGs2XXIygKYR2RO3qMYrYk2seTHWavm7nH31gv8DWUtnxn/sKjx5i3zRv1a1Y5SzBE6V1ko6jQDqD1QCkwZTRL5nqc+UaTtPCe5JSgs1mM2ZjgMAc5fvZ85NmX2q9Sezavjus2wwGw/uYKuoU9G3ShZgGmznFZbrbCyxyFmxPyOJKo0pPIuqLvvZkpkM2sI/UKzWtRptAh5qg4kZJos0Ohq6fF1RNjL9VxyYhHnPm8xNL3FZKkYSfS7SA8f+MiJWgXIf9h++KzenC2mw+PyK3SGYVYroj+cDrCaWU+xrRG5qdLI3H9rp4dtgVM+2ERIB1uquIg95ih4xd36o1n54suCqJXbjo6VHCxklKM1tfyZDqWtbf4m/BTln9l+QGBGvAvEu2mQz9yU8eHfb8UNYaJlWXtpLx7SwSTaC8h4hAx76YhK2TlhSnSACMhDX0o1zw/YShOf10SVXSQNo+zd/lDRSUwaY89QIMBAvz5pgOkdqeUvYgsovDcTRzhGNM1Qpe5CC5gF7osfGfMKsbx39vWmD4tXsix//XAZvBUUMk7I+MBvs3FAcP9GNesPPEo1Y33VeJJq4+/1bhWwdN0ukPBNQb7OzekdptsC3uAZ15A7rL7+JORk+LaD0Hq6dadIVfKWlm/qTluzR16b/FPP8KtqzMoyEGRPgpCY7JEwCkqmq2VG0abh0am7JcFA8aNY4QEMnXVVMekqVp8pWldd+WqIoRVms6mw4BolT/+q+RzKJhCkxo4kp8fjomq3KJ6Eo0=
