apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: planka-dburl
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    uri: AgAQp4OJywS3w1Umuu6IME28o6qSQyRMzhNLSy4wSd5Db1oaitRGdvl1pvB1D6xKIWCm1WqLDb9rSvFbGZWQcstpTAgVnn5cSVc2BHMW5pUmkAwiv7sjAHk/FxPGkoqVSUCP+4FQzRBVQal86qJijPpAdkAq0snWuu2OeDv6sgAy1+i7yPo7ldFcHFHjY9BDkpSErpfdD1GE4pSeXadgi/7UYDtpUUodvJrk6D3iYpoig3flqXqYXuJ+ZJhqEY8sd/ewTp87vS5jmNH8nO4PYrZkob5qy3wFRWOWLNLNwmCGGbp6P7vGCSeJ1KKZbkYxUU7dg45ewSBUJh0qfiL0bEsXCwNoOn8YyDqgemYAjPD80z69gvkvCf9UZanfE/6MSthuTSmnOIXKx2Q0K1AJlNTzQ5ca7y+q9lkkxMfgPRXyK+5AigmkdHWbXUw7Az3+UEuRx1vFxdWmcKBARXb3uf4Fa/qjqPyg5fMbtBe3b1x6bBoKGCqj+zAXoIuPDsKgD5gJEAnWSvkx88viqMPGq1lXqJExv1+370wsqEiCXad0LS69N+Q0RIRqmDcCXtn+FeqrRcEEUM7ugAVmg4z6SqI+R59IpWeDgzRP0xa1NVWNiPshMrCKdSGPKZkkxgBNBefYKV9BrNX8d/Z7C+Rnl458pm2srCpjx4bEHnCvFoYC4mYKoU41zpxZ+Ihhlp5eqz0yB99iI1kcYK7Mopb+3hNa47lfzIEFjllGcgVSJ01IlIcr3sBZCazj11BgmfoxvMQe04ek/cqBHewMA9S+31mrgBswcHrTBeyeGUt2fGl2wUsBdATTx+qWFwdfmJfd6/wZEFo=
