apiVersion: v2
name: docker-registry
description: Deployment chart for docker-registry
type: application
version: "0.0.0"

dependencies:
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: docker-registry
    version: "3.0.0"
    repository: https://twuni.github.io/docker-registry.helm
    alias: registry
