rails-application:
  name: filamentory
  image:
    repository: klausmeyer/filamentory
    tag: master
    pullPolicy: Always
  environment:
    sealedSecrets: true
    plain:
      DUMMY: "true"
      APPSIGNAL_IGNORE_ACTIONS: "Rails::HealthController#show"
    secret:
      APPSIGNAL_PUSH_API_KEY: AgBBSaYS5IueXB/Fmwn9RabbAIMClqrgttGlAEwhNToWM/QqJKCkR0I+jWC+OWe6kfttB3NVFt6g7RP5MxHETNzF2dt5lef52SlD+gkYcKyrDI+ETHVwq8zK2GoOMo2NYZiS4qmIwNQN9eIAnT4XO5d1pG8LKVPsw09VKO/5HSjI4dE5F+kd0pE2MlPgEAL+FOkKfvFBisySUldg5T2Eo26svn9WyIfR1YaQ2LLeeXEJn3gd7L8RI6YuxLFRXGlR6LrjFuhYoTAvJ12lwmub57CE+7wDKV3+AcEaKQrqjFQYI8Yv+3V5QgPF3u35FQc32EPUI8cMfbVB9oOK51t8JeyOx1fBcXB/kPdJEOHLUfER/0LWr47cACVJeriMJpxuilkiY5a8bY3tGRY1E1ZvP0mWf91VuCfvXZj1dzll6DoOi7d04+u4HCngJAUH0q/lkTqbeaKZoQJD1iBirNqWw4jmW9aQhQanJnyEDwLbEDBROH8RcrMxMMQKwSV1ldegmeKxDKltPR0yWXfc2PBpjZLJJQqV3om4xKB8P11Z1TJ9omCUQao8DdSfFh3MwfYqypZ+g+INt2ItBRaK9+Es1BYVQXZqF5GlARapPfk5SpYo8iwCeDqr4reByDeKscnjaXGojmsgQpvTazE47Ou4yK16LBNG+JvcVXu63WkUe7oqbi1N2fUwBVh6G2e8vs2fpSiYP/MYyzrqokPluOreS0E4twwI6L1CeOHn/PrHmLNuz/4Ik5w=
      DATABASE_URL: AgAT6nS4z9lCd9NK+eAIs+ejrcmV9gDgPlPjJMKmk3esbj36+/fAa32BThLKtDGm18AQ0cQLpiKDy7yMjAlcIUHQybl+27/5CRx6DHZ5CnT1ePgyI9mUFMsHwp7Qoz5++AlpEdJ+HH5CvrxJniWyG66XXofuoG2QVjpaR0duDi/I+lehGSeyLJ2NyFncesqNkPWmj7aDtgo8ZT+qmL2oSJ0SP4MwkHtrKZhC1LWFcc54APTJJuwjmbk72OuXIdANE0j8GNgfLxQpmj+Gcu3M5OLdJVphI6cXlJJb2REcVT5qM1ZGjklncVe4dYZdgYXlEQ9IT9YV6G3HcGvsfinV5owkANPFr+GMfHW7BNazuO2DX9ivlPvz2ER43NdxOXj12A8WKMn0OdUOAnC+jkxLt0+CcKYi6PTS1QZWHj0DVTrtzSRiVfivSU7NQGqY1uICCRW0yyLg5WRD7ub4uLRq21xhRevAp6UANIO0pr81ch8c8md5aCjEV26/doy19mAIFNoGmGLZCItSwnr9bI4AG07Uhcd5eU22wCCpscnDIWJLi6Q3jhC/AabX8LfTl6R5Qzb7OQ6Q89FU8WffOuv5A4sdjaOt49Y9BpYD7XV/ugCGcY6XtEHkwpByleUuwNBQICNKFY5CXcDkCSyndt9IcAMTRGxGwCyNiS9cst25AgURkiqD2niQ6hxPvr1RVa2oM32QMYOWBOn99NOkngOIpow0Olqftwj6lHNJ/NDnVVcgfI+fkB/bRBX4mvyIrGSjNk1ga4oJXQZy/QsFLP/hcRNentrQugs1Bv2n1udsbsRfKn5hQfe3H/Dh1QniMvleFf/nC8q8mN+TzW1PCBgRkf86
      SECRET_KEY_BASE: AgBZ18QfpS6fPUkGXXyM76UjlfzrlrdUeW/TBLosVyLvw0oqJQ2d4h39bIlfQzrHqfrcYXjtU3RGLQrUTH9PKwp8hdmGgkGY0j5dlD9TvxY5+sH5R5YAqIc0HQxFYZc9AySV0r8UBNJ1MCDYMzW/sthY6io1+SMNLY5RuU2OJWKR2sEd46UCB3P4IGqdR9+xoH5ptDyy0bddm3O/hIcZN6G60kIW/9XbcWrjLQwND3JlPem0Oar7WvOvzyB7888D/FkLZfNTXDW9XrgLkUleqYpOKEV+/4Y6WWsOXpCY/+9NdvWVT9Ad2hw+mJoXaCjpxQBcD2k4XXNI+WdXGXQ/64bfHeQ41Z+WO06UJkLX4vYyUaOrgwUVrQ3Me+E1Ov7iL82sAxQKpRDODA21WooXQoINvhrj/UbAHJxl5k2YveWCSP+cF1kMNoK21CcKIyEfKRjqnh3W2XUdaT7KeIRdHipGNguP0AzxAwDt0lpoPgFw1tvAUI3dmyKcpv3gWWZSTzRn+ZO7vFAQlMbV1Knvg8pguJSuERA1a0gAn9M4vUc9/qwjp8mw4LY5Q/EO+H8zZK0kFszPotYk/U4gOmAIulOzpn0D1ZzlXrNnhAun4mF34gUs/odD0elZ5haVF7MqIz+6rkDPtAgjAYp3ICyNiOKZyvhK9j3UoE5ojh3RPhXUPEu+eiKFGjygVmc+P3n58o9V9dczKyFdzP/1tCXJKK+bwNAyORc94zmKI9rD2CnGlBvHB3l0ZtMuoQ10xbS+VqxtAFkl6A43/0O0MnOWpdqQ1yRAd28btgM1SGSn1OfOjJ01UGdaBywFPhzUbUEKHAKyQyzIDx/u8kLTFOVmZ9kvNDwnBxBW2xTLpV0CF2yQHw==
  deployments:
    web:
      livenessProbe:
        httpGet:
          path: /up
      readinessProbe:
        httpGet:
          path: /up
  ingress:
    enabled: true
    hosts:
      - host: filamentory.home.klaus-meyer.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - filamentory.home.klaus-meyer.net
