planka:
  existingSecretkeySecret: planka-secretkey
  existingAdminCredsSecret: planka-adminuser
  existingDburlSecret: planka-dburl

  admin_email: spam@klaus-meyer.net
  admin_name: Klaus Meyer

  ingress:
    enabled: true
    annotations:
      nginx.org/websocket-services: "planka"
    hosts:
      - host: planka.home.klaus-meyer.net
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - planka.home.klaus-meyer.net

  postgresql:
    enabled: false
