planka:
  existingSecretkeySecret: planka-secretkey
  existingAdminCredsSecret: planka-adminuser
  existingDburlSecret: planka-dburl

  admin_email: spam@klaus-meyer.net
  admin_name: Klaus Meyer

  extraEnv:
    - name: BASE_URL
      value: "https://planka.rooster-piranha.ts.net"

  postgresql:
    enabled: false
