apiVersion: v2
name: tsidp
description: Deployment chart for tsidp
type: application
version: "0.0.0"

dependencies:
  - name: common
    version: 5.2.1
    repository: https://bjw-s-labs.github.io/helm-charts/
