# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-5.0.1/charts/library/common/values.schema.json

controllers:
  pg-backup:
    type: cronjob
    suffix: pg-backup
    cronjob:
      schedule: "0 22 * * *"
    containers:
      main:
        image:
          repository: klausmeyer/pg-backup
          tag: latest
          pullPolicy: Always
        envFrom:
          - configMapRef:
              name: "{{ .Release.Name }}-pg-backup"
          - secretRef:
              name: "{{ .Release.Name }}-pg-backup"
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN

persistence:
  pg-backup-hooks:
    type: configMap
    identifier: pg-backup-hooks
    globalMounts:
      - path: /opt/pg-backup/hooks

configMaps:
  pg-backup:
    data:
      DB_HOST: postgres-rw.databases.svc.cluster.local
      DB_PORT: "5432"
      DATABASES: filamentory,gitea,grafana,keycloak,pantry,paperless,planka,release-tracker,whatchy
  pg-backup-hooks:
    data:
      before-backup: |
        curl -sX POST "https://appsignal-endpoint.net/check_ins/cron?api_key=${AIRBRAKE_API_KEY}&identifier=pg-backup&kind=Start"
      after-backup: |
        curl -sX POST "https://appsignal-endpoint.net/check_ins/cron?api_key=${AIRBRAKE_API_KEY}&identifier=pg-backup"

rawResources:
  pg-backup:
    manifest:
      apiVersion: bitnami.com/v1alpha1
      kind: SealedSecret
      metadata:
        annotations:
          sealedsecrets.bitnami.com/namespace-wide: "true"
      spec:
        encryptedData:
          DB_USER: AgAGf+nsNbW0xsnhstalAfuKjF04W6xWm+N6LSakqjc0n1FmdHAOMmRCyl6C1k6xiaoF8SVnf417mR8GOG1aWQ0oMmfDTZzLfD8iUtuCvU7qNzMCBYXbv+YYq7w+7vEzpIenBQQH5jYRGPdM08DxXAd9RHJtzJndHtx0UIpDF3YID39hsL4uzQSEDFiMInqRPM+VHz8fJi3OKBoOOZtFy9HNvMYx0bwFGpPTxZ1LkaHnix7+dDZmspxJHef96CpUIIBDR9aJBG/fgIRe8fa7TxpB5p0f0edDVfLOjhBZAdaWIVgiICvP7V1a1jKQWYz9tJjTsaHNwr5mNR5ZN1REDu5FGeM24vVLDbWGC4Vf/DQOJRxhqew0yzjOy+CdRjsuOLTafJMGNUQYFzR5/r3Y8u6AxHpPwkD4lZGXEpbloVCzQZrQB0U/B7NQN3+qVkOY7ZYUSzWglU4ARphTMLhvSh6/UecDNncJgpjTe4cSwTgTs/tTNkcABF8c22MOB7MIdoPm9xE3ZRJc0d6/Nt3On2lKHMvP9AOI7nZh8u87+S0Gmg7NofMvWuejSZ/J0eHvMypYZgl8ZM7b7i1v410UZ6J4mLOKVt7jGlPkYaoHLC7R7f1HWnvVPdQWj1WiXYRsM2taAtiOgaXH+7dZr2Jr5SsQAw4vAh/LX45DW6R9Uei7uTl98hUO/lNqwrJo5det7Swosv4fk5V3Wg==
          DB_PASS: AgAyOhqBBnZ7ITwIVUUo5D446VnoIrR7xq3e3fwV5IDaV/Fo2Si3l1EH2S4GLBYgkisRMffb1koTUGzNajehmqVI0e9Adiq9HRBcr/XJEehja7CRY99vm2CuJJCHS4/U42+hc0e7xKxinPOaqqDhv+g67QSf1TYdejuNqbzdo5jDhQMd2XVR7S6xG22CIQsHYdaERRmesXklBTLxpyO4t4me1GFz4JWqZ1h4ECUW5vcB1S1rhE0eL2ybP9s2TFiwjI8yKBoTo7fe61s4NJZKgVNf+mlRM5fAZqyJZT9AuJJCrLEaSS4UiYJSAnUrtQ03NeFgXUcvfRZTxMKOsXrJCQ32E9yLb9wpiKTpZXJ38RA+/S+bxq8FF/hk0rbeBYU+IiuELJ8RvZ/WgPA4j6F24w/ppSPN2euBQe4JXJR+dpHunOerb7mLkgb3iujSq474hxaXiPC2O9edBZFf9D5ya2MY41PMwoKVuXbmlt5UzxQotc+X1dxQDG8n6J48DBYvcm6+jPCk0Ivk4pB1NnzclGOoJB3R6ZO7PFzXNN/vcBfJRcgqXCFm3iZaACazN3E3CQzFxRp62NCKwRFf4+83jm77dnOqyjWbt8y9WaJrQpg0Szaptz0os8lCD4rPDKJsQDLcys/Ktyt/dQVFkZ/pdM85jHw/yvuqbTpcMJpWh2KnqaN1R9proCVWjxxOdc0T9UetcYBFHbylpdB5a6qwXcFFAXl+olgbTjweq4vFAymvn9HDaLR5Ug/tQAf9WDgEpiU9ElstqHihoONHAwFinQPq
          WEBDAV_HOST: AgAEyILKJ145vlUKvFiSmzIzZCebGNpbURc2MV6E3OTbm5tzc9/oeddeSqdM67iTagCpBpN8HoRq/vc5aGcHf8v2UFicFqbcqoIP8kd0FtbfXIL9udBLTb3wY5JiqjPq6Z76Qsa9s7SYVE6dMm0/ypOXDEeLBXKs3NRDLLono0qBdDMHpuZalIB9g+1tSjAbChmLe4SBUPLvOi0Tpg5aA8Trz3c7et+CwSdbg7w6AVjzSmVbxyPhgP0j7DAS2C+g4q4Gk0TQgl6M8iUF0rHKPVtKqt4mO6N0NO0h3fUZVxWE8U6irijUrTUcbqeayTpF5GMApV6PykxQ1GrU7W/7RUjMjoQ3jE1WauCXkzg/DHJtEQ5e3GroV+vQ9k3FbF2iOGIIUe4POJwNlmwPxzmNpvC7uNcBkG5rSN4RYTS283NZuZEzhDe2XnTaKFglxI8Ris1XPRLfHtTKZ7u5Y0jBPrPzkJ2VZk0n09VOmqlyYiS+4waxtNx1g2PatJhG6JJcKAt6arY45SytvS4Xfywy4PGBplBQnzw0UkGh3LkBgLmwpLWotcYEAvM2LtP91Ewpx481boC8d380uP1Kk4l3RD/I1+wKK2J51ZYWEdIJIOy1sLjZv5QdEzE9JGuuUIUP2o01QeBFquexdyzbiLRXB2eDfyVXdOpnoQL0qGkw98S9gCpLLOXMxXCTilVctSLlfLbvJKDyMbeyyZK5wtzJn8xTUkXHl/2hL4XCj3TzC0L0d1g5KPaEQ7c=
          WEBDAV_USER: AgCDQo4IySo+3xTh/dIGCNzTmjWmXQBadjT0YBDQH0BmkUNJO2WQwnRKIDRNOb8Iat+NAYjB0AQ1KLb8BoLvOL3PvB63oLRmaKczJ36I2r96ak7qooEgMRgOrm0SYNxqQvndzJfn0R4rzkgC7Ay7iCuNtsGY5+Ko9bQbT1bBYwF76ZlCkOcX7wvCpElTJ78N0H1Jt85zoDPcXY9MexWcFwEKn7aMTkqkSSb3Y+wS9dmccdZiKpb1p+9/zKuLcOggQ+6jdQa1+g7U+wzgVEJgPaqd9tTYKN8BGXtn1Hvajh3bLmmmzJCGSfs4pq3o8m2xBXOMjcZ12GklzOqGAXhYIB9JlYTV9MhaGHuZBM4JTs9Bxvx3DOLek+2yPx8xthhGLMUwVZCbDKdVWvzrOjX68ChrtHkTit2RjAHG4C8FjMt+V/CXLfZ+hpYSduqLMYrOkfUbekMwNjAPw7C2HnnVQ/Xlk0LTGWs2zcf5PJj9GLyLSS/Q4+MW8TMFVdwTFCoxiW4PE3zU/Q0Ba6Spt1qpWXXJ+pFOcnPZttWgPMUHIrZkf+lIuIuSrytHButLYBcjgwdHF8YQVYGu+a6p8431ohtm5t0o1oqELn0KOzTl6kzVAg1vbXxaoFU7tRxJ8lLdO4azF4gj2xDAQM8qOXy3Ao5KHEmTzzNtoq20oensJALQW+b6M/Yx+A+R27w9XGod2XiNu0mYLJwhJutR4Bo=
          WEBDAV_PASS: AgAsAF3oNlZQD5dtkT0ibZ9ALuFDWWuVbLILGIMmaUPjdc7xJyfBl34LLNN3coL/K+QG71odVo+fAuEmF9j9K9Yh4YXD2fva0MZh/va8hxZ/8QmI/4IgJTsqfV9wt4ve3IsHYHNFixJP/aAKi1NvtCLPoN0981xpbXcPOIKl4WVGKac93MMuQKRPWXe1I9Z7D12kSOc+jzRXKQC8cQMHgqt5ZPd5SQO0TaAjwwT3gEG/ctrDY9bTxBipIMdUJFqXZdlQYsWf6V/2qz1GIk8RLqLMmyMyYI1nwfNN46V+OzKK5RdHUrdh0UCPOoKeAvweJBEHPxthsKl/U+xMlOZeORahbAvYK6PcXw5eEtC2LB4DIf/Ng9rOXbPlDIl0I7WqyBcg4rv+f/LTeI053nFl6tCdYmLM4M9o6WvdD0krdidwwrpHvyMC1BJ4bksCc4/sdtRo3xw70kiYY3STwrn+ndaHN8X51hmASVkaLmoKgYbS83BETXIuGS6r3XEKKQgIOerrQBp/GLqXgaEMoM+ZJ40Nq43y4O+dWaxWCseMxWYnSoGcv6uueIvBSRaFLKQgtkOhNierf85/VqXGFvC3KtnKpYXiQu1oiT43BAqwAYycHZKh27BK4Cflxo4c04A+nBrW2Q5E/kmm64NiDLVRWKkrjvTC6srafI81UNPi85aAwTNNItWDYGUjRJ1vkHD41JcizuEI3CE/NSmBHGy4jPtqWZIT+w==
          WEBDAV_BASE: AgAUZ/jMELEGktcvCou1Y7ZQ67iA9unTrHDMIrIfZdTImd28SrJRmrEkc8blyGiA772kwyLO+Lka9XmeZGIlMFrPWRHWHYjpLH/3ITWSwJPzkFwuQEtC2fu6I+NeXuqU9wJg2wvgVIIgBUNz/wdSUEJMnawKU2qDUWC4yKcbOED4h8lZaMEiJPZPg3FWhJe+nJxtWfdGEZhHUgJlZ7FfSEa33MHlJV0m70f+s92FiPQ7uN1TuUeSFWjC5pqlWJAZfUkUYVitI/rypdkfFRP6unc7pPjjXWqiPxDJ9uuLYb4nSNQNXS8KgwNDNLd4zx2uF5EX2BYMTLFmncfeBvlhl3Q0LodLiXXr+qqzjqCd9StTDVDoP0RaOQc83HC+xr2P6wpnS7pCK9R8w2K/tEVtjBbuLwYeTT4vXbGU6E9jwvtX7+Fwb7Dt4mX0x65ZcjqUZ+r5X2TbB18tnpYId5f4sdZFRj1zxiCJ0DenAvyj9pSfo9DsDM5Btttv2tle17tzwEaKGb7AHGpn1t9MyTdxtheGuGVHytA4NDtbGC1K+ZfT/kSWLSzEsjEZLQr3zlpOgR1U4ebHH+bDkaTUfzfTzBPcA/IDt1O8MK8zgRmZUCBfGadLuw9CfQk2N1pGXVt6kRSJy1AxCD4HfEu5PqCIKeBFYpcpIc2vITxRiwdD1JUpILWF0ygOKm3edU58M5z4vuERflGz/dxIO0Pkzks3
          AIRBRAKE_API_KEY: AgCjtKVQuiwoQOsLHyeBZ8PI6EY8JaB5dEvdi3GuW4Z6/Qi3h0w3F596B321FdhtyaCDLNWt4gVQkxOo42M5bE9SuacIkkDs4fOroNCdyLvA3/Sw4nYi493/s5Nc/toAXMqfqW6jXVZN7uRsl+vjXda1tO19Vj/PsM4OXPjSDbO50B/EF79aR/4SoviguonJ86hm2s0YZ8RVgEFRphPAIsjyvP4ET3n0Az05ibXxuIwUpDgxBbFZ/tMRn5GLlKusEQKWdsf7JZr6IsK4Agub9OkV9n7HsqHuUo/88vt7UP2B0DMJxLVUrawenrJ5vTKSrW9YrCS8OjVlUtf4e96NKXd5sXlnqGSMpR3WiwCftZJL2yAa4QsLjlTdZ8F68W97ariCoW5fpClpGCAq5Q9MEgeWXkAmpdDD6gqnoYUKgvUIpXpOhdFnILUHQaTjP4rLKvXUwCk7oci8pVw9UStxxx1P/VFx5pHB9pMqAe+8gwT3et4DIBqZG+hK24dKg8T90RRlMqGGOqfPgtame38YgQcCjbDlNnekqwrinkjB7b3JARn5ZgHFuPELlJmcXva5r1/mSKPAg9VJu5Tzs5BEBd/Fiz3U4udXC0K7JITlOo6QIPb85d7AAl9S3HPTs2Ro+QSVIHxqePKfz/VvtucWwBCL4lOY0WpccVMaAGzQ7NmNpJF4oWfOadqDHPk5/liTEUTzgwAfPSWHKOAXhdAsAUIS1J7P7z7omeAC38zXMEpo9xcgh3Q=
  database-superuser-secret:
    forceRename: postgres-role-postgres
    manifest:
      apiVersion: bitnami.com/v1alpha1
      kind: SealedSecret
      metadata:
        annotations:
          sealedsecrets.bitnami.com/namespace-wide: "true"
      spec:
        template:
          type: kubernetes.io/basic-auth
        encryptedData:
          username: AgAf+QNFouKjG/SQp4b/FA9Zi8KJJ2Ya4ZDdhaKeSdiR5ceMLJquTlRHekaOcbzvKjiyRGP87z4oT2Vs0kxbQlGpXKhrb/KFtKrqBdYzm+Q75V+O/fvMTzvZbCU9RJvCn9Jr7K13Dtzu79xuFBZwEBdemdU15DL4xFyvKGwL5gO5goghwHUY7A6DLHlX9MoYzLOkd4zi8GGAo3ncBWcrocbqFXLWda99qyXcs1sU8Po3tJ1W5peffSmF2mzZw+s/qH2AA0NN+qzBAbYsCsKDsrsXw4MszAv6XJJSiP7nIfcvRyC2RQOCfo5Pq/7biLRoAAgtCR8iwe1t5g326mqECjnYxQJSV8NjFDDXAcL83IRRJNO4MF4iDl52B2PSuH5yZrSDOTgMV6/Wc+h5pxhC3lJ/VxYmk/1+TjSJTyrHVPEU7kOQ1b2yAswWLy4Lq41ywf30+jsqy9q/1DPMx9xvshZwMi1l7Xfqrve3mnfjj1KAS45ueWziXmk86aQF73jWT70Pb6osmSIE34t280G6dWgEEsB+VOmwgR90TgbU5cAYH3SNxmIqm/Lm6pv774fIb9WEJWVOn0WiM0stfIXQM4WYpycCwQHMKrrg1m/MqU5dhbF+XS7kDi3pe8WcvPX50/UtQh8Oz9ajodTMPHKkdwRZEQgrhR+j0MZsQeRHtMiOz3xok5BGClQYFWkiT6eJv633/sweXQwRxA==
          password: AgBvttRgF7OMdaKFRY51/F88W8gbhKD1fuOMVG8iyIfXHxUHZviPjzCtLmi7uy8ndACNa9i+MC/HDT0P5gziQBDq+ifcfSB0UVQCBftvFKo5Vz2EB7OQJNG+zhxyXq9jCEDkB14eAJcSdif+RYyjnh38o++z2Bt2rWjN7ydfCKL/Ijsv3XvF++oE1wgeOCmaSXf5hOOTi8/JvhCOZt/RZFClGNiMnF/8YcbsQGrusLhMO/Mb0Qv0NUhN45Rir6UEFMegOUR2Q71qOXw0o50kXHR6fAkZ2ayIMQZRvNV8fwTo+7cNIvljKkEZfChUJl5i9AGCfqwke++vkFP1vRoj356ea6aqKGkkTEAJ1dkgu/OPvw+I1HG38yBew6QQ7WwSeOQVW6F2dekfFRfVBUzR1V1m44uWyPVl/r/r/TZPR9ejrEHjTL4pj37+KXj2k8I70mO0S2OdG0qMRGXANs8eXdyCXDf3rGjkDARyFLkzvp8J3r/1+pqmvwPvW6kl2QUdvTFn3kv3UWZsBXl69ecXdX7Bc0DertejmiYoxLjyKppps8KkfVyJ1wsETu+1xETpDiRu412ZxQiykYPfjdeT5atRfzJQGfIYP6a83g30sYF7JKF1xLjTsrI4yUxObkrjEVBk5yud69CYv3h/uvFwtDsDj2URr8qui6KiiRoAIU3RpWN7+TXCzkPU+n8HG7/XoRsJAT88a1UEugehgg6RLkvC6eLpG2wKPn6ByxyiU0Qizq1qwX03YM3FPsOnOT7bZ2yIlqK0XpYplRsYCD60LHvG
  database-role-secret:
    forceRename: postgres-role-backup
    manifest:
      apiVersion: bitnami.com/v1alpha1
      kind: SealedSecret
      metadata:
        annotations:
          sealedsecrets.bitnami.com/namespace-wide: "true"
      spec:
        template:
          type: kubernetes.io/basic-auth
        encryptedData:
          username: AgA+envgNThEyJVB4GEvKBoDeiHTboR2YMx98XByH2jo6lycXoN4QQ7/vvepnDVLUArBACcr3ZYU8XmF/eQqlWFwNojbDuemjUBup2zNA4yzQmffVb+09BRhegUAGCIFi8rX2HPVCZyLQCsQMUyh3vUKi+yiK2+0nOJ5/2L9UvbKITr025nYOFKj4f8YNcNOzD4dkksC3fpzlTKIyxVMjD6U+h6zJk7iLV57KYR5ZSjHc7ePPkyBsGQvGE8yrRULq13E5zGyMggxvvg6jQc0Bq3GyQAhL5iC3WFNcJxNNsgwCxbIuT8DuSitNwL7QctQtSh+GclxDiunapNHMdBtEhBw+TcrJ9sSlP7WOpCujNrBvQWaaZ3z2cRtoWPy8nsZ8S6XDw6CBGz2R+0YN2/AWvvMPkQyUSYOB5qI35alkTuU6YDMhRH/ksc6Qi+d5HqaFdfzRx2Gvs065l8HC32qnDp2C1wizKyxpRs+iU10sbtrCW89aekaL9oNAohF9R5DoMjUOZAOeflAeqYNhD7SZ88EUkhghaqBOrh8cGeYrpVqyK96gSFP59hfD6m7lm+MjcDfEMmz34zqMCOkjL4QkG7IY8gQlK03NRf6F2x+8osst1jUnTyhDpm5xDwHA+lhXN+fLDfYV4tyQpY1PT453vJCDzkDz7MgAAZyE7X8B9B42PAjGn+3J5o0x/aynSSixq62phX5bak=
          password: AgAoAiU4Zl+/TZ8xLZz/2TzgWcmZ6UweUeSOodanEADBy4UdFj7v8Xv5MqNAUNwDbQpJkz1z9g3adXWyF6eZ5Ey9ecBHPbbLOE/CLpQ+2OraZyQ2S+0Z3tdxKQQIhv6ZBb3ZlEal6E0e56JVnNK8d55mTgtNQVVkYnLWTRsrPvCWSprn/CNMvgEtc+ndB6L8XR7R6ychsThSFhuAkoCmN5tlnP3tkAlwoQbq1TV12Rvfpb/243TYLf8lo/hZFCeSQ+68Qzzwz7A52pCzZQZhc5x6bY1lWilKHSLSSISkGn89suX/8DmGH/K71vMxcKAFM/Pb3klzL3ARO37qKkqUrUAk7zUtDZVDeDaiSgjB/mDV+uOX60dwrVZHbL8PgWS+eSdQesp6bD9xaiQQkFWuwXH7gi8PlxFHNIjbat7z6A0n+/ImRSVxSNBZJVAUyGf4fJ6UIMgVXISgdLyulNxLGF7/+gJKncCQfeWJ1CmxP6wMe9vkqD7ry+g/XiZ3c+kRI7Iu8xQsqwXePvR74rrbx1h3Ewjagg/vueJfEpRHxIP6sY+ZHfsudTmKy9vQ9C/+E2AuHbu7CqENnY/hILM3aWG2zOJvDvOfw7L7UGcc5i4C9x6KBpQa+mXtrALPRGu0ZGgssCiYnj5xGTnmVEiBWROTDZPPOb7Ia70h6ykuLcpR3/VGEiJF9hqbB55L+EBhs3bAAz1vJNgPVdG70QM61tPu/YXyoJHlYbTeje5ogwfOcTVO7HYr31a/jjZWzRgsB5qVTQguKjLtQQlBAtdjL1zn

cluster:
  fullnameOverride: "postgres"
  version:
    postgresql: "18.4"
  cluster:
    superuserSecret: postgres-role-postgres
    roles:
      - login: true
        name: backup
        passwordSecret:
          name: postgres-backup
        inRoles:
          - pg_read_all_data
