bookstack:
  envFrom:
    - secretRef:
        name: bookstack-env
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        cert-manager.io/common-name: "*.home.klaus-meyer.net"
      hosts:
        - host: docs.home.klaus-meyer.net
          paths:
            - path: /
      tls:
        - secretName: tls-wildcard-home-klaus-meyer-net
          hosts:
            - "*.home.klaus-meyer.net"
  mariadb:
    enabled: true
    auth:
      existingSecret: bookstack-mariadb
    primary:
      persistence:
        enabled: true
