apiVersion: v2
name: gemserver
description: Deployment chart for gemserver
type: application
version: "0.0.0"

dependencies:
  - name: common
    version: 5.0.0
    repository: https://bjw-s-labs.github.io/helm-charts/
