apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: databases
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    superUserPassword: AgBL9w1q/sk7hS6V/AfmEaTh7LQO0lPxP/fSgTUAiKjBgu8MknopFCVk4Sv6b4rH56ytnmsluAFJO40Bqf/PwaI9Fv6O2SQvBT62y8YisWwGdL61+HILUtycbAqoFdwJPV3EB2x/1AJCmFaBEc6N4S7LfyqeOd2FmquIM6oMOHkZ7Ky9RwujBGRXW3PG/eHRpU9Igipuq7D9IUbcvCW18Z8fTA8CFYR+dT1NjDAOlskVTXuuVwU3zrFcf4ifuoAht+uQ6xi8ayuXC5KPZeM5U66iG91tGSY16hzt3tG04mV7Ud+2Oy9MEPRjfkV6dwgjznL4G81V4DKU7ldHV8oOoY2pk8GJzLeEKHXpuC1GOsKwF8H8RDrMOfBI3W2i1YAOmorrtwgPLCohCbpJf750NKsK3yL6W9ag0rpXV4lV4J3aS9qAJaEmOdwOyd3xDg7ck1v+ZyjCznSytFSzN8WPyQiFsy6pyMfmKh9EiJYu8zGdn0uDB2mmWul3TkQHI1Vq2lqOpzUhz6mkTdZB3yIxRTpsqedSKGoS4W/LzAEY948xaerL3pH3Nw3ib4Yco7jLdCh1u6UCNnigZqkENN/5iT+zehu1iqOaqGo5sO8siyu7WfKhY7aP7F41MVan3OHsWi54vUGjehQqlBT2hpNa9Ep3rt18Ogg2Jnuis2jgdKVRTImx5TgArKfeUoZPKot2VDYrNBw5uIH2IAcC6mGzo5AmaEOpHRg3CICdCOwM8aCHVg==
    replicationUserPassword: AgBsuH5nAFW2RxXVcUmRqTCsFawAjr2RRqyADMbgbqbHZFVtrj9K7VzlqNd5kGH9vXnMaDLVA0+YJVHFrPd+utQCktNe2nCOhlScorlyf8sKmYMneWTS+AVT3uDjFNCZc9FJSvXMF8SEUFPrDBWZljfoqfhnCNdnrWgr0xruf9xrg1JypJJXo7l/Z3Hqn6E9M3kXHfOsDaVOe689EPNZvNdgZTTFo2WgeaQTHzkL0zSgpFHWkZxOOZpN4RzLJGvaFv15HvM4XxlyBo3tK84a7BGuAFy8vsS/IYNgYnUO1bjg/gJz6qgh4hC2FVVfWysTKxUeaNSMxYnuzzLBb5QyWPRXn2tksoPhhQPERFMNAuvM30ZpzCCEbJvPKLCYwcg5r3Iu7MhhQRhlFbJauh2oCVL9V5CdOmWKzw02e/+9O88Fk4UhRFpbW8/X1SoTYG375zubQmjOn1wtgV5nYDlBzid6xVIm0KWCzDJG0c+2919A800D7xHCon8qtIAnMR33qnjqFDq5ZtDWUu4w+nx7YSZfyMjicWcYgiGj8VWJgxECfC3CGbZ3+4DAqP9WCYLL+e9XQDHHsa+T5jc2nEz6h1kfYWY1XNJLcNcOKMfhFBcMqr1K25vWNHPI75LsapGIZ/VFjM92HYB3iPPJ90FFIXDCO2HHD8yJ7f4BdqKd13le0Uzsvr7HYDPt6N/nZN43ghBlVQkXJzHUWH+UdoPVh7nNO+0RKNqgX813XD9YATgcAQ==
---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: databases
spec:
  replicas: 3
  image: postgres:17.6
  database:
    size: 2Gi
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: superUserPassword
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: replicationUserPassword
