apiVersion: v2
name: longhorn-system
description: Deployment chart for longhorn-system
type: application
version: "0.0.0"

dependencies:
  - name: longhorn
    version: "1.12.1"
    repository: https://charts.longhorn.io
