oauth2-proxy:
  fullnameOverride: "oauth2-proxy"

  config:
    existingSecret: oauth2-proxy
    configFile: |-
      email_domains = [ "*" ]
      upstreams = [ "http://longhorn-frontend" ]
      provider = "keycloak-oidc"
      oidc_issuer_url = "https://idp.home.klaus-meyer.net/auth/realms/home"
      code_challenge_method = "S256"

  ingress:
    enabled: true
    hosts:
      - longhorn.home.klaus-meyer.net
    tls:
      - hosts:
          - longhorn.home.klaus-meyer.net
