controllers:
  gollum:
    enabled: true
    type: deployment
    defaultContainerOptions:
      image:
        repository: gollumwiki/gollum
        tag: 6.1.0
    containers:
      gollum:
        enabled: true
    pod:
      securityContext:
        fsGroup: 1000
service:
  gollum:
    enabled: true
    nameOverride: http
    controller: gollum
    primary: true
    ports:
      http:
        enabled: true
        primary: true
        port: 80
        protocol: HTTP
        targetPort: 4567
persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1G
    # retain: true
    globalMounts:
      - path: /wiki
ingress:
  gollum:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      cert-manager.io/common-name: "*.home.klaus-meyer.net"
    className: nginx
    hosts:
      - host: wiki.home.klaus-meyer.net
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: gollum
              port: 80
    tls:
      - secretName: tls-wildcard-home-klaus-meyer-net
        hosts:
          - "*.home.klaus-meyer.net"
