apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  namespace: databases
  name: postgres-role-keycloak
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    cnpg.io/reload: "true"
spec:
  template:
    type: kubernetes.io/basic-auth
  encryptedData:
    username: AgBwuzhjM7biUnjLEGN/kyLnVkeOL6fY6yoAi33XWDnkvo0l4h8zHFphOXRaEOcEX160TdgPoGKla4DsMzlLD2KeCTJSkeSBCbl3pa/KZjvznWazse0R6DqlcRDohSdI8zXU0C9WKb+IKiNaxySAiwfy5umZPlttQja7kZ0b3y47DJFiDXgiBt/yxx1mL/Nfc66uINp+wuS1ee8l5EcbdRJzQzJWu+nrArdHRPR0ZI2aDY9HyYg8srfYIvFULbZ91Nzmx44Y7XGhGMXTP03aKSTB1EZg7JIO46+aNlsNEtZXcnH1FoqtD7Tok1HJe4er+vMC2DfIrOLZjlvWWWzSe55PQNJn4RkHsJQ3BV7XLUXfyL9BDyrlEP75a9C+m2FvtNvdP/FmPFJisN5dhdUbAASzo/DyKoz89YJ2I5l5ZSQ+FEfK0AGcQikM4JuyxfVeXapKgFdS6B4MGGFgZ8B75OjNdB++UeP5jqwVNVDtSKrb2SMruYCa/f9ePAB45g1VwJsf2CrN+e02gdbUKbsiNMhCMhm0MOMKSkx5c7bmAG1q5A85DO82oB8XoZp8wzcCKICPFbSC1oLrb77cNs5Nc51Klic50Kq194sG2rZf4vaW1JFw3ki3uw1FVy43SPlcLhc46PQJ/DZSUPn4fXJ9mzfh9498PHo2/G2qeLJm/m8gzM32iuJmatUnnPPfSFlNPh7/Trt/wbEHNA==
    password: AgB7Tv1Y+XedwalB1niOVYBmoM4zPmrAg/XFRlTJKgdQIB/pldzNupUOufowGZdAoTUP0XnqrAXtWZF6YxpT0QzLpIvzAH9S258J5U5GOXYA9oQ4dX2elcK52VbCz11PqWpIXoJZ19jIdqIsXjalEQII/uWysaV3l41xXG1GeEERWocJF+TgXtmAEc0k5bxQH8HnI+XpaN8KClPSzxIbCzLYeyGtatUe2Xlbyb86v6oJQ0VY3y7U93yBSfXxPpmVYZ4BxtvSqwOek6SDhuYzrw7bLev7cQHDBcdh2hh0bbT69K/XR1JPHIZ2yOZRdpEvPVKf70WUPyAyxMKSEpxaVOIw0Urbu/PNpzfjxgHWaQPOCoXrdHVcpl0lVoX+l7rMTTREBFruFtMEaMB3nLg69bxcB+ktAoSeMSGALpuvVlIV+IQZvWGw6H00srSQzFuwdHay8sgCUu59a1JnyY79GmcL8wNj0OFmgc9c+6UX0MkZwb/lQg/eW3WhlTeYfyLrKVddWGbqwI0lQvxlOctXUft7g7XMMHLBnDM7EvKJFsWgmJPMkZHDKkSKxMXBoj+Nb4A6M6tZ4TmJ8Kkxo9Nl73V+nWaVRAk+tcPh932JGvE2HS78cfOPefyE3WJ6tm6WdVVL1zT3yMZZdF/QMATSWklBl2YM48c/rEmQlsBn91gtcUEAIyss18JSajCY7Mt48zji4ZRwEwT9cDXS0l0CaW1zykbm0wPY2uM6ZMxTw9639g==
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  namespace: databases
  name: postgres-role-keycloak
spec:
  cluster:
    name: postgres
  name: keycloak
  login: true
  passwordSecret:
    name: postgres-role-keycloak
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-db-keycloak
  namespace: databases
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: postgres
