apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-database
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    password: AgAoWCwLLxmz5wNdLcTV8opP9tTNW9BrkAqIlSgh36QzXH7uIAhIBJV1HaxzZYvH4Q4M2S6VcmfkaxXY161apjx0k72zSFZD0BksLeVnR/qR3odtG5r2t5SJz7smFb8fwRl11xTAJ3Ru4jMnUmUsZGPk1cdP+H5o2Brh/o1xwNtG2i0a6nEgwzFO+EB/mX2zHMQ4egz99e3nmFYkCUQHfM4up7AknD2Mhz3XWx6G/7zkDz6L4Jaqtp/M9J1KgcLNdX8ShFu6otE3cQ32klta7CnFxbB/ZagJmSHZ7yXQ1RSARIRpDDhlonzhzhrD4j7ubDXP5vGrgNIm5LHADkepOUWyvYgZn0EL/Xn9RE5MBhhRw6ezvA9xMvJTLXt9EvQU5F9TpaRahP6kWRcAh6vfNxR7egcvhoxrPgBRW9cGu7+7Gvz87txBxzl7bZPUFx3Sf+/8N5wnAcoTPdwmwjxA/HbN6hc3tOZo9eGoLy7G/kAwyEs3mDFf5aDWXtyMMiC1i9mdBbgH80RJOrwxO6BN5/ogOfDKETHsP+1Kl/nyr2Gv/LA5UhQEYFUZ1aGCPxIqcI/h0X0hfvTK6rcPjQw8J0DLPvrhtXYLgsmtjHT4mKtUcfIzsGulQcCNtaYemRcVkQB8BIWcAvdPCiPnPpWENDHMhceHCwYmpHC8gPrZFNxEDIJ8/JkV6DRGA3LuwdMmXtVJPEJ82019Mng6udpETqCr5tM3PsmQRA6DUnnD7Mqr5w==
