apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-password
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    password: AgB7qjVVD6k+6nsQgyHH3cji+WVOWiC+WHmaBPiTvSwaYZDeqVLaX+XuS7+0n6N20HDkLAAGS3WWT8gO2LsHpYMfWpEQ4qqw8em9I2KNCYXcYAg/rEnGqd4nQFh94zYQDqHyJ/bx/aL25dVJ/eGA2lY0w03qD7M6pODlz35iYT8MSdraUE5/8Sc0Sm6diMBUMa+4ppBqfNjzYwDksaOiQk7+KpyFzkkwmpvYFpMvLfVKgVBCMgeLNPEud6nOnXL4sEXKnc9iej6WnMmDo2tboc7toSxrtFma2lZETqgu5ev6A4HO8qOTvKsIIsfdTh4DIxwYb7CySymGXhbe3PWYDC0ra2FuEqXzhr9Gtp8QqTuntkbFXGUCNfzwhVm4Ewcrxe9gXAFB8F/5LDpPmRgtErNfRQtuyBHTvjEQGZU+twIP5/sq5pxkOVjUtMNxJRBXfrl7Be0dyBs9Lvvm+Ii+lj7d4DEjYKi9YLJ5BMbXnf7wZjExvI0Ra4xeIRbCFtYZOxNHIiSJxx3551hC2svcUF1bm6z7i4Q6ITjMbiimTJxS0/8rbgzLra/HFYdOm2yW7hjHfAUCCM4x3G3Qhr+WIT9IjzgUpQhp2htcZSwLSSNcepv5QdLfHeNkwhRm7YFrleJjfbafpdd6KjKKmagDnNoE2+/uwyTuVnkZfjg/OcEAGWcyOwqqVTaRDw2sMgf9i086RRwszxcK/wnq+OZ1LA==
