apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-password
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    password: AgApscqRAv3eqRxKMHdG8+pmGPrNYwAJDF5N128B6SgBIFiuK6v+oSw5tLhcEH4d9OsvWSZGjMvUi6Yml39dIxh8COcQ/RJ1a09WWF0c1mLVeyhhbZ2YCVDqNTIwHvL8dOmhZFqse491KmRnDq0GMRSSl6TnGaQWvJyXSDX5tyauoI1VMpt4ouw9r8Ato54xzSwKVufinmsFKdZHP7jDPKomWrLXfuoHzGkmESVTMiGHcD4u9N2SLcqPbVjGiTrfCxNNtZVpGB23Q1CVza1IvX2B53/ymPh4//iuUPa9k260dREPzPB2pqJ+iXoiuHs8+6aLFspWoswrkdOE9vPCpLHI0jui4OWd0DAqTP1Kcg2us9GPoiK1d04LPjC1FgTOGN8MzfncjKAcHsi5z8uGJbv403uk6cMpIWMejVr4mW3rwvStQpcyJGLUHyUbj9TSnu65GDu18rOR6fXkbIDNdrX3AGlS4xuPNPI4Kh5PAkXVDMNgQistz64uTa4wj2R2fyF5DLyvBYf4zFhgQNKXjo5xGnxrUKdfg4gmJpGqpDq8Zk8qfi5Kpihi6MFtjib7sfcJUNQyGBgjzwKqyrGeVxSv1U0iGIVMBzNgbP7FDST/XVTzvNFY3FYxzePIzAV6G21X7leGzAzN4VHLh5gnhLa0/986DZlV9TkneRMoyfutgvC4E12JakgLVoRCUjmRUmHQvdx/4g==
