apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-database
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    password: AgAAwdqjMbZ1BgfFKfc/vNSaOmLBZJzvWqSCUG8Pw+xF0BZOvoCyO9xgD52WOFoYWv8GzGAJE+l82HSykIWxZIwEyfY971g5LcXmIOhzgpxhEsH+yWc/g6ig4Y7BUxOSkwIyHEVC2EljzYbw58MZyA2+1zYgx8E8GMoMaQY01Jy0gIFiwL4MnF+F3hG0VjCxSY1IGkX0R8NvvnGXrMKKZwrqRtoDnffLWaDkJ7e451eCLMTlgom6PSV9rSCagGxAFg0FrQma/rCUrfTvwfwn/iYWlrWPMIE1+r0ImR8mN/AkZMJ9Ue9dhGK9KyrWVz8Xen0c+5vfzcwKONZvUrFx9k2RqDE/eE328Ky+VdFk2T67looczezQKM7XnrSBAX66OXWFg4oOhlHFsh6dUj4+pB2TqI1iNsTkCLpZNJWc6JkyDVLGd737ZQ7aQxJYpjNwjStMphi7hy7yP+jp1YTA0HMpPUBNbEciOnyuKlTCgQuD6mKQZ8E97grtQedWC5PaDXEEppJFOpPFzF6MdZWte5VnZiVzgoaUkqE7WCYgur4i7XzLjQh92HakaVVKLzNsveZXHTZoGXjBaipUDcqdDx5S1+Pv461LHyh79hBS+ZeqvjxC8yoIFLoVHp3V/9rYZH56nOJ/cuQGuOdQ+PEuSJn0CPJYSGQkOsdtu3spzm0i3eE8G/BQPIiL394aKF36g1HzTypwm1lQem06MNnAGrnfEkKqLBngBSA/V7BUGRmGOA==
