garage:
  garage:
    dbEngine: sqlite
    replicationFactor: 1
    s3:
      api:
        region: de-dahoam-1
        rootDomain: ".s3.garage.home.klaus-meyer.net"
      # web:
      #   rootDomain: ".web.garage.home.klaus-meyer.net"
  persistence:
    enabled: true
    meta:
      size: 100Mi
    data:
      size: 1Gi
  deployment:
    replicaCount: 1
  image:
    repository: dxflrs/arm64_garage
  ingress:
    s3:
      api:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 500m
          cert-manager.io/cluster-issuer: letsencrypt
          cert-manager.io/common-name: "*.home.klaus-meyer.net"
        hosts:
          # -- garage S3 API endpoint, to be used with awscli for example
          - host: s3-garage.home.klaus-meyer.net
            paths:
              - path: /
                pathType: Prefix
          # -- garage S3 API endpoint, DNS style bucket access
          # - host: "*.s3-garage.home.klaus-meyer.net"
          #   paths:
          #     - path: /
          #       pathType: Prefix
        tls:
          - secretName: tls-wildcard-home-klaus-meyer-net
            hosts:
              - "*.home.klaus-meyer.net"
      # web:
      #   enabled: false
      #   className: nginx
      #   annotations:
      #     cert-manager.io/cluster-issuer: letsencrypt
      #     cert-manager.io/common-name: "*.home.klaus-meyer.net"
      #   hosts:
      #     # --  wildcard website access with bucket name prefix
      #     # - host: "*.garage.home.klaus-meyer.net"
      #     #   paths:
      #     #     - path: /
      #     #       pathType: Prefix
      #     # -- specific bucket access with FQDN bucket
      #     # - host: "mywebpage.example.com"
      #     #   paths:
      #     #     - path: /
      #     #       pathType: Prefix
      #   tls:
      #     - secretName: tls-wildcard-home-klaus-meyer-net
      #       hosts:
      #         - "*.home.klaus-meyer.net"
