garage:
  garage:
    kubernetesSkipCrd: true
    garageTomlString: |-
      metadata_dir = "/mnt/meta"
      data_dir = "/mnt/data"

      db_engine = "sqlite"

      block_size = "1048576"

      replication_factor = 1
      consistency_mode = "consistent"

      compression_level = 1

      rpc_bind_addr = "[::]:3901"
      rpc_secret = "__RPC_SECRET_REPLACE__"

      bootstrap_peers = []

      [s3_api]
      s3_region = "de-dahoam-1"
      api_bind_addr = "[::]:3900"
      root_domain = ".s3.rooster-piranha.ts.net"

      [s3_web]
      bind_addr = "[::]:3902"
      root_domain = ".web.garage.tld"
      index = "index.html"

      [admin]
      api_bind_addr = "[::]:3903"
  persistence:
    enabled: true
    meta:
      size: 100Mi
    data:
      size: 1Gi
  deployment:
    replicaCount: 1
  image:
    repository: dxflrs/arm64_garage
    tag: v2.4.1 # renovate: image=dxflrs/arm64_garage
