garage:
  garage:
    dbEngine: sqlite
    replicationFactor: 1
    s3:
      api:
        region: de-dahoam-1
        rootDomain: ".s3.home.klaus-meyer.net"
  persistence:
    enabled: true
    meta:
      size: 100Mi
    data:
      size: 1Gi
  deployment:
    replicaCount: 1
  image:
    repository: dxflrs/arm64_garage
    tag: v2.3.0 # renovate: image=dxflrs/arm64_garage
  ingress:
    s3:
      api:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/cors-allow-origin: "*"
          nginx.ingress.kubernetes.io/cors-max-age: "3600"
          nginx.ingress.kubernetes.io/cors-expose-headers: "Content-Length"
          nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Range"
          nginx.ingress.kubernetes.io/enable-cors: "true"
        hosts:
          - host: s3.home.klaus-meyer.net
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - s3.home.klaus-meyer.net
